repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://github.com/pycqa/pylint
    rev: v2.13.7
    hooks:
      - id: pylint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest
        language: system
        args: ["test_hello_world.py"]
        pass_filenames: false
default_stages: [commit]
